// @generated by protobuf-ts 2.9.4 with parameter long_type_number,optimize_code_size,add_pb_suffix
// @generated from protobuf file "auth.proto" (package "com.nookure.staff.api.proto", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message com.nookure.staff.api.proto.AuthRequest
 */
export interface AuthRequest {
    /**
     * @generated from protobuf field: string username = 1;
     */
    username: string;
    /**
     * @generated from protobuf field: string otp = 2;
     */
    otp: string;
}
/**
 * @generated from protobuf message com.nookure.staff.api.proto.AuthResponse
 */
export interface AuthResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
    /**
     * @generated from protobuf field: bool expired = 2;
     */
    expired: boolean;
    /**
     * @generated from protobuf field: string message = 3;
     */
    message: string;
    /**
     * @generated from protobuf field: optional string token = 4;
     */
    token?: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class AuthRequest$Type extends MessageType<AuthRequest> {
    constructor() {
        super("com.nookure.staff.api.proto.AuthRequest", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "otp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.nookure.staff.api.proto.AuthRequest
 */
export const AuthRequest = new AuthRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthResponse$Type extends MessageType<AuthResponse> {
    constructor() {
        super("com.nookure.staff.api.proto.AuthResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "expired", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.nookure.staff.api.proto.AuthResponse
 */
export const AuthResponse = new AuthResponse$Type();
