// @generated by protobuf-ts 2.9.4 with parameter long_type_number,optimize_code_size,add_pb_suffix
// @generated from protobuf file "player.proto" (package "com.nookure.staff.api.proto", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp_pb";
/**
 * @generated from protobuf message com.nookure.staff.api.proto.PlayerModel
 */
export interface PlayerModel {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string uuid = 2;
     */
    uuid: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp lastLogin = 3;
     */
    lastLogin?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp firstLogin = 4;
     */
    firstLogin?: Timestamp;
    /**
     * @generated from protobuf field: string lastIp = 5;
     */
    lastIp: string;
    /**
     * @generated from protobuf field: string firstIp = 6;
     */
    firstIp: string;
    /**
     * @generated from protobuf field: optional bool online = 7;
     */
    online?: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class PlayerModel$Type extends MessageType<PlayerModel> {
    constructor() {
        super("com.nookure.staff.api.proto.PlayerModel", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "lastLogin", kind: "message", T: () => Timestamp },
            { no: 4, name: "firstLogin", kind: "message", T: () => Timestamp },
            { no: 5, name: "lastIp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "firstIp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "online", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.nookure.staff.api.proto.PlayerModel
 */
export const PlayerModel = new PlayerModel$Type();
